[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.19'
via_ir = true
# optimize = true
# optimizer_runs = 10000
# See more config options https://github.com/foundry-rs/foundry/tree/master/config